# Generated by Django 4.0.6 on 2022-07-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
                ('temperature', models.FloatField()),
                ('sky', models.SmallIntegerField()),
                ('humidity', models.SmallIntegerField()),
                ('wind', models.SmallIntegerField()),
                ('rain', models.SmallIntegerField(default=0)),
                ('description', models.TextField()),
                ('scene', models.ImageField(upload_to='scene/')),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
