# Generated by Django 4.0.6 on 2022-07-22 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
                ('temperature', models.FloatField()),
                ('sky', models.SmallIntegerField()),
                ('humidity', models.SmallIntegerField()),
                ('wind', models.SmallIntegerField()),
                ('rain', models.SmallIntegerField(default=0)),
                ('description', models.TextField()),
                ('scene', models.ImageField(blank=True, default='default.png', upload_to='scene/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
