# Generated by Django 4.0.6 on 2022-07-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathercomment',
            name='scene',
            field=models.ImageField(default='default.png', upload_to='scene/'),
        ),
    ]
