# Generated by Django 3.1.3 on 2022-07-20 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_likemarks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeMarks',
        ),
    ]
