# Generated by Django 4.0.6 on 2022-07-14 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_weathercomment_scene'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathercomment',
            name='scene',
            field=models.ImageField(blank=True, default='default.png', upload_to='scene/'),
        ),
    ]
