# Generated by Django 4.0.6 on 2022-07-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_delete_likemarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathercomment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
