# Generated by Django 4.0.6 on 2022-07-15 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_alter_weathercomment_scene'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weathercomment',
            old_name='publish_date',
            new_name='date',
        ),
    ]
